version: '3.7'

services:
  bootnode-el:
    hostname: bootnode-el
    env_file:
      - docker.env
    environment:
      RUN_BOOTNODE: "true"
    image: merge-el
    build:
      dockerfile: Dockerfile.el
      context: .
    networks:
      priv-eth-net:
        ipv4_address: 172.16.254.10

  el-1:
    hostname: el-1
    env_file:
      - docker.env
    image: merge-el
    depends_on:
      - bootnode-el
    ports:
      - "8545"
    networks:
      priv-eth-net:

  el-2:
    hostname: el-2
    env_file:
      - docker.env
    image: merge-el
    depends_on:
      - bootnode-el
    networks:
      priv-eth-net:

  bootnode-cl:
    hostname: bootnode-cl
    env_file:
      - docker.env
    environment:
      RUN_BOOTNODE: "true"
    image: merge-cl
    build:
      dockerfile: Dockerfile.cl
      context: .
    networks:
      priv-eth-net:
        ipv4_address: 172.16.254.11

  cl-1:
    hostname: cl-1
    env_file:
      - docker.env
    environment:
      NODE_NUMBER: "1"
      ETH1_ENDPOINT: "http://el-1:8545"
      EXECUTION_ENDPOINT: "http://el-1:8551"
    image: merge-cl
    depends_on:
      - bootnode-cl
      - el-1
    ports:
      - "8001"
    networks:
      priv-eth-net:
  
  cl-2:
    hostname: cl-2
    env_file:
      - docker.env
    environment:
      NODE_NUMBER: "2"
      ETH1_ENDPOINT: "http://el-2:8545"
      EXECUTION_ENDPOINT: "http://el-2:8551"
      LIGHTHOUSE_GENESIS_STATE_URL: "http://cl-1:8001/eth/v2/debug/beacon/states/0"
    image: merge-cl
    depends_on:
      - bootnode-cl
      - el-2
    networks:
      priv-eth-net:

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/28
