version: '3.7'

services:
  bootnode:
    hostname: bootnode
    env_file:
      - docker.env
    environment:
      RUN_BOOTNODE: "true"
    image: merge-client
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      priv-eth-net:
        ipv4_address: 172.16.254.10

  miner-1:
    hostname: miner-1
    env_file:
      - docker.env
    environment:
      NODE_NUMBER: "1"
      RUN_GETH: "true"
      RUN_LIGHTHOUSE: "true"
      ETH1_ENDPOINT: "http://localhost:8545"
      EXECUTION_ENDPOINT: "http://localhost:8551"
    image: merge-client
    depends_on:
      - bootnode    
    ports:
      - "5052:8001"
      - "8545:8545"
      - "8551:8551"
    networks:
      priv-eth-net:

  miner-2:
    hostname: miner-2
    env_file:
      - docker.env
    environment:
      NODE_NUMBER: "2"
      RUN_GETH: "true"
      RUN_LIGHTHOUSE: "true"
      ETH1_ENDPOINT: "http://localhost:8545"
      EXECUTION_ENDPOINT: "http://localhost:8551"
      LIGHTHOUSE_GENESIS_STATE_URL: "http://miner-1:8001/eth/v2/debug/beacon/states/0"
    image: merge-client
    depends_on:
      - bootnode    
    ports:
      - "5053:8001"
      - "8546:8545"
      - "8552:8551"
    networks:
      priv-eth-net:

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/28
